### ISSUE TITLE
Booster fails to switch to next Engine Mode

### ISSUE THREAD

**Issue by TospTV** [Janus1992/KSP_Starship-kOS-Interface#1]
I got this Error after Stage Separation although Tundra Exploration is installed and the .dll is in the GameData Folder

![image](https://user-images.githubusercontent.com/61606069/177058813-c91e9b63-cab1-4d9e-80e7-38347da5a443.png)

**Comment by Janus1992** [comment]
That shouldn't happen of course, thanks for reporting the problem!

Was there a time when you didn't have Tundra Exploration installed and maybe saved the craft files? If so that would be one way that I can think of that may cause the loss of access to engine mode switching. You could try to reinstall the craft files and see if that fixes things, but otherwise it's a bug (maybe other mods interfere, but I could fix that).

Could you please do the following:
- Place a new starship on the launchpad.
- wait until the interface shows up.
- go to the first or second cpu and press CTRL + C.
- then make the cpus window a bit bigger and type the following:
- BoosterEngines[0]:modules.    (with the dot at the end)
- Send me the screenshot.

That would help me narrow down the problem.

**Comment by TospTV** [comment]
I already had TundraExploration installed before installing your Script, so that can't be the problem...

I tried typing in the command you sent in the Ship and Booster CPU, but nothing happened the 3 times I tried.
Then I tried printing the Modules and it looks like maybe some other Mod is interfering the script. I'll try to figure out which Mod is causing this issue. 

![image](https://user-images.githubusercontent.com/61606069/177209188-09ab666e-cf49-4027-855b-6a03e5ed075a.png)

**Comment by TospTV** [comment]
And here is the full Error message after i now found out that, when you make the window bigger, it shows a much longer error

![image](https://user-images.githubusercontent.com/61606069/177209881-a73c954f-5f35-445b-a4b3-ef25432bd384.png)

**Comment by Janus1992** [comment]
Thanks! That first screenshot was all I needed to confirm what had happened.
When you printed the modules you could see that you have a "ModuleGimbal" right at the start, which I don't have (and I guess gets added by some mod).
I used the bad practice to get a module by index (number 0, the first module) instead of by name. But I changed that now.

Can you try out the new version that I just uploaded and see if it works for you?

**Comment by TospTV** [comment]
Thanks for your help! This problem seems to be fixed with the update. But there is now a new problem: A few seconds after stage separation i got this error.
Seems like there's some problem with the gridfins


![image](https://user-images.githubusercontent.com/61606069/177335637-6ac1c6d1-a425-4e39-9f8f-15e65a349aec.png)

**Comment by Janus1992** [comment]
Weird, since that module is part of the plugin of the Starship Expansion Project..
It should really have that module.
Could you try again, and when it fails mid-flight type this in the booster cpu:
print fin[0]:modules.
Do you have any mods that could possibly interfere, and if yes, could you try temporarily removing those to see if that fixes things?

**Comment by TospTV** [comment]
I found out that the mod Atmospheric Autopilot changes some modules (see image). By removing the mod everything finally worked as intended, so maybe add that Mod to "Doesn't work with" in your infographic. Thanks for your help and for the amazing script!

![image](https://user-images.githubusercontent.com/61606069/177643942-c85c62d2-e95c-464c-8c50-c53899c509d2.png)

**Comment by Janus1992** [comment]
All right, I will do that! Thanks for reporting the first bug!
